from django.conf.urls import patterns, url
from django.views.generic import TemplateView

from argus.models import Party, Category, Group
from argus.views import (PartyDetailView, GroupDetailView,
                         GroupCreateView, GroupUpdateView, GroupLoginView,
                         GroupChangePasswordView, GroupPasswordResetTokenView,
                         GroupPasswordResetConfirmView, GroupEmailConfirmView,
                         GroupLogoutView, GroupRelatedCreateView,
                         SimpleSplitCreateView, EvenSplitCreateView,
                         ManualSplitCreateView, CategoryDetailView,
                         GroupRelatedUpdateView)


urlpatterns = patterns('',
    url(r'^$',
        GroupCreateView.as_view(),
        name='argus_group_create'),
    url(r'^logout/$',
        GroupLogoutView.as_view(),
        name='argus_group_logout'),

    url(r'^(?P<slug>{})/$'.format(Group.SLUG_REGEX),
        GroupDetailView.as_view(),
        name='argus_group_detail'),
    url(r'^(?P<slug>{})/edit/$'.format(Group.SLUG_REGEX),
        GroupUpdateView.as_view(),
        name='argus_group_update'),
    url(r'^(?P<slug>{})/edit/change_password/$'.format(Group.SLUG_REGEX),
        GroupChangePasswordView.as_view(),
        name='argus_group_change_password'),
    url(r'^(?P<slug>{})/login/$'.format(Group.SLUG_REGEX),
        GroupLoginView.as_view(),
        name='argus_group_login'),

    url(r'^(?P<slug>{})/password_reset/$'.format(Group.SLUG_REGEX),
        GroupPasswordResetTokenView.as_view(),
        name="argus_group_password_reset"),
    url(r'^(?P<slug>{})/password_reset/(?P<token>[0-9A-Za-z]{{1,13}}-[0-9A-Za-z]{{1,20}})$'.format(Group.SLUG_REGEX),
        GroupPasswordResetConfirmView.as_view(),
        name="argus_group_password_reset_confirm"),
    url(r'^(?P<slug>{})/password_reset/done/$'.format(Group.SLUG_REGEX),
        TemplateView.as_view(template_name="argus/group_password_reset_done.html"),
        name="argus_group_password_reset_done"),

    url(r'^(?P<slug>{})/confirm_email/(?P<token>[0-9A-Za-z]{{1,13}}-[0-9A-Za-z]{{1,20}})$'.format(Group.SLUG_REGEX),
        GroupEmailConfirmView.as_view(),
        name="argus_group_email_confirm"),

    url(r'^(?P<group_slug>{})/m/add/$'.format(Group.SLUG_REGEX),
        GroupRelatedCreateView.as_view(template_name="argus/party_form.html",
                                       context_object_name="party",
                                       model=Party),
        name='argus_party_create'),
    url(r'^(?P<group_slug>{})/m/(?P<pk>\d+)/$'.format(Group.SLUG_REGEX),
        PartyDetailView.as_view(),
        name='argus_party_detail'),
    url(r'^(?P<group_slug>{})/m/(?P<pk>\d+)/edit/$'.format(Group.SLUG_REGEX),
        GroupRelatedUpdateView.as_view(template_name="argus/party_form.html",
                                       context_object_name="party",
                                       model=Party),
        name='argus_party_update'),

    url(r'^(?P<group_slug>{})/c/add/$'.format(Group.SLUG_REGEX),
        GroupRelatedCreateView.as_view(template_name="argus/category_form.html",
                                       context_object_name="category",
                                       model=Category),
        name='argus_category_create'),
    url(r'^(?P<group_slug>{})/c/(?P<pk>\d+)/$'.format(Group.SLUG_REGEX),
        CategoryDetailView.as_view(),
        name='argus_category_detail'),
    url(r'^(?P<group_slug>{})/c/(?P<pk>\d+)/edit/$'.format(Group.SLUG_REGEX),
        GroupRelatedUpdateView.as_view(template_name="argus/category_form.html",
                                       context_object_name="category",
                                       model=Category),
        name='argus_category_update'),

    url(r'^(?P<group_slug>{})/simple/$'.format(Group.SLUG_REGEX),
        SimpleSplitCreateView.as_view(),
        name='argus_payment_create'),
    url(r'^(?P<group_slug>{})/even/$'.format(Group.SLUG_REGEX),
        EvenSplitCreateView.as_view(),
        name='argus_even_create'),
    url(r'^(?P<group_slug>{})/manual/$'.format(Group.SLUG_REGEX),
        ManualSplitCreateView.as_view(),
        name='argus_manual_create'),
)
